### ISSUE TITLE
Grundstruktur för dokumentation

### ISSUE THREAD

**Issue by sweco-sedalh** [Eskilstuna-kommun/geoportia#3]
Vi vill börja tidigt med dokumentation i projektet, så att den kan fyllas på successivt. Vi använder `mkdocs` för dokumentation (samma som Backstage).

- [x] Skapa filen `docs/requirements.txt` med följande innehåll:

```
mkdocs-material[imaging]>=9.6.12
mkdocs-include-markdown-plugin>=7.1.5
```

- [x] Lägg till följande kommando i package.json: `"docs:_base": "docker run --rm -it -v $(pwd):$(pwd) -w $(pwd) ghcr.io/astral-sh/uv:python3.13-alpine uvx --with-requirements docs/requirements.txt mkdocs`
- [x] Kör `npm run docs:_base new .`, detta bör skapa upp filen `mkdocs.yml` bl.a.
- [x] Justera `mkdocs.yml` till ungefär följande innehåll (fritt att justera, är i huvudsak taget från annat projekt):

```yaml
site_name: GeoPortia
site_url: https://eskilstuna-kommun.github.io/geoportia
copyright: "&copy; Eskilstuna kommun och andra bidragsgivare"
site_description: Metadata & tjänsteadminstration för geodata
repo_url: https://github.com/Eskilstuna-kommun/geoportia
theme:
  name: material
  language: sv
  features:
    - content.action.edit
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github
plugins:
  - privacy
  - search
  - include-markdown
  - social
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Hem:
    - index.md
    - licens.md
  - Användning:
    - anvandning/index.md
    - Kom igång:
      - anvandning/kom-igang/snabbstart.md
      - anvandning/kom-igang/installation.md
      - anvandning/kom-igang/konfiguration.md
  - Utveckling:
    - utveckling/index.md
```

- [x] Skapa följande filer (kan initialt vara tomma):
    * `docs/index.md`
    * `docs/licens.md` med följande innehåll: (skapa även en tom `LICENSE.md` i repo-rooten om #2 inte är genomförd än)
```
---
title: Licens
search:
  exclude: true
hide:
  - toc
---

{%
    include-markdown "../LICENSE.md"
%}
```
    * `docs/anvandning/index.md`
    * `docs/anvandning/snabbstart.md`
    * `docs/anvandning/installation.md`
    * `docs/anvandning/konfiguration.md`
    * `docs/utveckling/index.md`

- [x] Lägg till följande kommando i package.json: `"docs:dev": "npm run docs:_base serve"`
- [x] Verifiera att dokumentationen kan öppnas i webbläsaren och ser rimlig ut (även om ganska tomt för stunden)
- [x] Lägg till workflow för Github Actions (`.github/workflows/documentation.yml`):

```yaml
name: "Documentation"

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/documentation.yml'
      - 'docs/**/*'
      - '*.md'
    tags:
      - "*"

  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/documentation.yml'
      - 'docs/**/*'
      - '*.md'

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get source code
      uses: actions/checkout@v4
    - name: Configure Git Credentials
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
    - uses: actions/cache@v4
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: |
          mkdocs-material-
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - run: uvx --with-requirements docs/requirements.txt mkdocs gh-deploy --force
```

- [x] Verifiera efter merge av PR att sida finns tillgänglig på https://eskilstuna-kommun.github.io/geoportia, ev. krävs extra konfiguration av repo

**DoD:** Automatiskt publicerad dokumentation
